version: "3"
services:
  drachenlord:
    build: .
    environment:
      DISCORD_API_TOKEN: <your-discord-api-token>
      ENABLE_RANDOM_JOINS: "True"
      LOGGING_CHANNEL: <your-logging-textchannel-id-as-integer>